sudo: false

language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '4.1'
- '4.2'
- '5.11'
- '6.0'
- '6.1'
- iojs

cache:
  directories:
    - node_modules

after_script: 'npm instal && npm run build:local'